//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbxUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbxUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        internal static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单位不可转换.
        /// </summary>
        internal static string UnconvertibleUnits {
            get {
                return ResourceManager.GetString("UnconvertibleUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厘米.
        /// </summary>
        internal static string Units_Centimeters_Long {
            get {
                return ResourceManager.GetString("Units_Centimeters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厘米.
        /// </summary>
        internal static string Units_Centimeters_Short {
            get {
                return ResourceManager.GetString("Units_Centimeters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英寸.
        /// </summary>
        internal static string Units_Feet_Long {
            get {
                return ResourceManager.GetString("Units_Feet_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英寸.
        /// </summary>
        internal static string Units_Feet_Short {
            get {
                return ResourceManager.GetString("Units_Feet_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英尺.
        /// </summary>
        internal static string Units_Inches_Long {
            get {
                return ResourceManager.GetString("Units_Inches_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英尺.
        /// </summary>
        internal static string Units_Inches_Short {
            get {
                return ResourceManager.GetString("Units_Inches_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公里.
        /// </summary>
        internal static string Units_Kilometers_Long {
            get {
                return ResourceManager.GetString("Units_Kilometers_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公里.
        /// </summary>
        internal static string Units_Kilometers_Short {
            get {
                return ResourceManager.GetString("Units_Kilometers_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米.
        /// </summary>
        internal static string Units_Meters_Long {
            get {
                return ResourceManager.GetString("Units_Meters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米.
        /// </summary>
        internal static string Units_Meters_Short {
            get {
                return ResourceManager.GetString("Units_Meters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英里.
        /// </summary>
        internal static string Units_Miles_Long {
            get {
                return ResourceManager.GetString("Units_Miles_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公里.
        /// </summary>
        internal static string Units_Miles_Short {
            get {
                return ResourceManager.GetString("Units_Miles_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毫米.
        /// </summary>
        internal static string Units_Millimeters_Long {
            get {
                return ResourceManager.GetString("Units_Millimeters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毫米.
        /// </summary>
        internal static string Units_Millimeters_Short {
            get {
                return ResourceManager.GetString("Units_Millimeters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弧度.
        /// </summary>
        internal static string Units_Radians_Long {
            get {
                return ResourceManager.GetString("Units_Radians_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单位不可识别.
        /// </summary>
        internal static string UnrecognizedUnits {
            get {
                return ResourceManager.GetString("UnrecognizedUnits", resourceCulture);
            }
        }
    }
}
